### ISSUE TITLE
Bitte ins Uberlab! 

### ISSUE THREAD

**Issue by microfx** [flowdx/crm114_u7#3]
Hallo!

Vielen Dank für diese äußerst leicht zu folgende Anleitung! Habe sie sehr im Uberlab https://lab.uberspace.de vermisst und hätte mir einige Tage Kopfzerbrechen gespart.

Viele Grüße!

**Comment by flowdx** [comment]
Nabend :)

Danke für die Rückmeldung und den Vorschlag mit dem Uberlab. Du hast recht, da gehört dieses Tutorial definitiv hin. Scheitert bisher an dem Aufwand, der das wäre: Kürzen, übersetzen, in das uberlabtaugliche Format bringen.

Darüber hinaus habe ich im Lab kein Beispiel gefunden, das auf individuelle Zusatzdateien setzt, so wie ich das hier tue. 
Ich vermute fast, dass es deshalb in dieser Form nichts für's Lab ist. Werde mich mit der Frage aber mal an die Ubernauten wenden, vielleicht haben die eine Idee!

**Comment by microfx** [comment]
Was meinst du mit Zusatzdateien? Copy&paste geht nicht? Kürzen wozu? Ist alles genau perfekt von der Länge her - wirklich ein sehr sehr gutes Tutorial, bei dem keine Frage offen bleibt. Es funktioniert einfach. Besser / kürzer geht es einfach nicht ;) Habe übrigens den Tip von den Übernauten bekommen.
