### ISSUE TITLE
Probleme? mit crm14

### ISSUE THREAD

**Issue by lanebe** [flowdx/crm114_u7#4]
Hallo,
ich habe nach der Anleitung das Paket installiert, aber es tut sich nichts. Ich kann Daten in die Lernordner stecken, die werden auch verarbeitet, aber selbstständig wurde bisher noch keine Datei geprüft und markiert oder verschoben.
Testweise habe ich mailto im cronjob aktiviert, bekomme auch schön Mails
I will show the mail to CRM114 now...
auf der Shell sieht man auch, das die Mails dem Programm vorgeworfen werden, nur automatisch tut sich nichts. 
Das Prüfscript aus crm114_u7_tests habe ich laufen lassen, es gab ein Problem mit dem Eintrag
MAILUSERNAME=[!USERNAME!]             # <--- Benutzernamen anpassen nicht vergessen!
Erst nachdem ich ab dem Kommentarzeichen den Rest der Zeile gelöscht hatte, lief das Testscript sauber durch.
Wo kann ich noch drehen, damit das Script richtig arbeitet, ich füttere jetzt schon einige Tage Ham und Spam zum Lernen...

Danke

**Comment by flowdx** [comment]
Nabend! :)

Danke für deine Rückfrage und entschuldige bitte die leicht verzögerte Reaktion. Ich helf dir gerne und hoffe, wir kriegen den Knoten schnell gelöst!

Du schreibst, dass ein Problem besteht, dass "selbstständig bisher noch keine Datei geprüft und markiert und verschoben wurde" sowie "automatisch tut sich nichts".
Ich gehe davon aus, dass du dich damit auf den Anlernvorgang beziehst, und nicht auf die Erkennung von Ham/Spam bei eingehenden Mails. Zum Feststellen, wo es hakt, brauche ich noch weitere Informationen: Wenn sich eine oder mehrere Mails in einem der Lernordner, egal ob in 'als Spam lernen' oder in 'als Ham lernen', befindet, und du anschließend 'crm114/learn_maildir' manuell oder via cronjob aufrufst: Sind die anzulernenden E-Mails dann anschließend aus den Ordnern entfernt?

Ich frage das, weil ich mir nicht sicher bin, ob du das mit deinen Formulierungen meinst, oder ob du dich auf den E-Mail-Empfang beziehst. Wenn du mir dazu Auskunft gibst können wir weiter nach der Ursache suchen.

Bzgl. des Prüfscripts: Da hast du in der Tat einen Fehler des Prüfscripts gefunden. Es erwartet die Zeile ohne Kommentar. Das werde ich in Kürze ausbessern.

Schönen Abend!

**Comment by lanebe** [comment]
Moin,
also sowohl der Cronjob als auch das manuelle Starten von learn_maildir funktioniert. Auf der Shell sehe ich z.B.

Looking for mails in /home/xxx/users/uwe.
	Eating spam now: "/home/xxx/users/uwe/.0 Spamfilter.als Spam lernen/cur/1602426058.M713961P3912.xxxx.uberspace.de,S=4293,W=4373:2,S"
	Size of the mail: 4kb
	I will show the mail to CRM114 now...
	Successfully showed the mail to CRM114 as Spam.
	Mail was deleted from spamfolder.
Done looking for mails.

Also klappt das. Der cronjob wird alle 20 Minuten aufgeführt, CRM114 soll aber doch beim Eintreffen einer Mail aktiv werden und das klappt bei mir scheinbar nicht. Wie ist da der Mechanismus?

Schönen Sonntag

**Comment by flowdx** [comment]
Genau, CRM114 muss in den Empfangsprozess eingebunden werden: Eine ankommende Mail wird CRM114 gezeigt, und entsprechend der Bewertung durch CRM114 in das Postfach einsortiert. Erstmal gut, dass das Lernprozedere scheinbar reibungslos zu funktionieren scheint.

Die relevanten Schritte des Tutorials zum Einrichten sind die Schritte 10.1 und 10.2
Aus deinem Shell-Mitschnitt kann ich lesen, dass die Mailbox (der Mailusername) "uwe" sein könnte. Mit den Schritten 10.1 und 10.2 legst du zwei Dateien in deinem home-Verzeichnis speziell für die empfangende E-Mail-Adresse an, zum einen eine .qmail-Datei und zum anderen eine .mailfilter-Datei. Dazu nehme ich jetzt einfach mal an, dass dein Uberspace-User 'xxx' lautet. Ersetze die 'xxx' im Folgenden bitte immer durch deinen Uberspace-Username.

Sofern du keine Domain eingerichtet hast (aber auch wenn du eine eingerichtet hast) empfängt die Mailbox 'uwe' E-Mails unter der Adresse: uwe@xxx.uber.space
Dies geschieht ohne existierende .qmail-Datei und ohne existierende .mailfilter-Datei standardmäßig immer, denn es ist die Standardeinstellung einer jeden Mailbox auf uberspace 7.

Prüfschritt 1: Sicherstellen, dass keine .qmail-Datei und keine .mailfilter-Datei für 'uwe' vorhanden sind. Dann eine E-Mail an uwe@xxx.uber.space schicken und sicherstellen, dass diese E-Mail in der Mailbox 'uwe' auch ankommt. Passiert dies nicht, liegt der Fehler schon hier, dann ergibt ein weiteres Vorgehen ohne debuggen keinen Sinn.

Nun richtest du gemäßt dem Tutorial die zwei Dateien mit den jeweils richtigen Dateirechten ein:
1. /home/xxx/.mailfilter_uwe          (mit chmod 600)
2. /home/xxx/.qmail-uwe              (mit chmod 644)

Sowohl bei den Dateirechten als auch bei den Inhalten der Dateien ist das ganze System sehr empfindlich, alles muss genau so sein wie gefordert.
1. In der .mailfilter_uwe steht folgendes drin:
```
MAILUSERNAME=uwe
MAILDIR="$HOME/users/$MAILUSERNAME"
MAILDIRSPAM="$MAILDIR/.0 Spamfilter.als Spam erkannt"

# Show mail to Bayes-Spamfilter (CRM114) if it's not larger than 2MB (=2000000 Bytes)
if ($SIZE < 2000000)
{
    xfilter "'$HOME/crm114/crm114' -u '$HOME/crm114' mailreaver.crm --"
    
    # if it's classified as spam
    if (/^X-CRM114-Status: *SPAM/:h)
    {
        # save it to spamfolder
        to "$MAILDIRSPAM"
    }
}
to "$MAILDIR"    
```

2. In der .qmail-uwe steht folgendes drin:
`|maildrop $HOME/.mailfilter_uwe`

Eine ankommende Mail an 'uwe@xxx.uber.space' sollte nun bei eintreffen folgenden Weg gehen:
1. Die .qmail-uwe nimmt die E-Mail entgegen und leitet sie an die Datei .mailfilter_uwe weiter. (Das steht in der .qmail-uwe drin)
2. Die .mailfilter_uwe nimmt die E-Mail entgegen, zeigt sie CRM114 und CRM114 markiert die Datei als Spam oder Unknown oder markiert sie garnicht. Dann wird die Mail in die Mailbox 'uwe' ( /home/xxx/users/uwe ) gespeichert, und zwar entweder im Spamordner '0 Spamfilter/als Spam erkannt' oder im Posteingang, entweder mit oder ohne UNKNOWN im Betreff.

Prüfschritt 2: Nachdem du die beiden Dateien eingerichtet hast sende bitte eine Test-E-Mail an uwe@xxx.uber.space und prüfe, ob sie überhaupt ankommt, entweder im Posteingang, oder im Ordner '0 Spamfilter/als Spam erkannt'.

Wenn die E-Mail-Adresse und der Name der Mailbox stimmen, CRM114 am richtigen Platz installiert wurde (davon gehe ich aus, wenn der Cronjob korrekt klappt), die Ordner innerhalb der Mailbox wie gefordert sind und die .qmail-Datei und die .mailfilter-Datei am richtigen Ort, mit den richtigen Berechtigungen und dem richtigen Inhalt gespeichert sind, sollte jetzt eine E-Mail an uwe@xxx.uber.space definitv in der Mailbox 'uwe' ankommen, entweder im Posteingang oder im Spam-Ordner.

Tut sie das nicht, musst du erstmal einen Schritt zurück gehen und testen, ob es dann funktioniert: Entferne aus der .qmail-uwe die Zeile, die mit '|maildrop' beginnt, und ersetze sie durch `./users/uwe/`
Nun wieder eine E-Mail an uwe@xxx.uber.space schicken. Diese sollte nun in die Mailbox 'uwe' durchgestellt werden, ohne Beteiligung der maildrop-Datei und somit ohne CRM114. Klappt auch das nicht, ist etwas im E-Mail-Empfang grundlegend nicht richtig (z.B. die Rechte der .qmail-uwe sind nicht 644), oder wir gehen hier irgendwo von falsches Voraussetzungen aus.

Mach mal Meldung, was davon geht und was nicht, dann schauen wir weiter.
Ich tippe, wenn das hier nicht hilft müssen wir mal in die direkte Kommunikation gehen. Mach ich gerne :-)

Guten Start in die Woche!

**Comment by lanebe** [comment]
Hallo,
ich bin ein Stück weiter.
Ich nutze eine eigene Domain, die identisch mit dem uberspace Account Name ist, also hier xxx.
Mail an uwe@xxx.uberspace.de kommen an und haben UNSURE im Betreff, was schonmal gut ist.
Mails an uwe@xxx.de kommen auch an und laufen auch durch CRM114. Aber die meisten Mails gehen an Aliase von uwe und die laufen nicht durch CRM114.
Für jeden Alias gibt es eine .qmail-alias Datei und dort steht jeweils drin ./users/uwe
Was muss da drinstehen, sodaß CRM114 angesprochen wird und die trotzdem dem Account uwe zugestellt werden?

Spannend
Gruß

**Comment by flowdx** [comment]
Moin!

Das sind doch gute Nachrichten! CRM114 funktioniert laut Anleitung also wie es soll :-)

Für jedes Alias musst du in der .qmail-aliasname dann auch einstellen, dass die Mail CRM114 gezeigt wird. Bei deiner derzeitigen Einstellung in den .qmail-Dateien wird ja direkt zugestellt und CRM114 nicht eingebunden.

Für deinen Fall, also mehrere .qmail-alias auf eine Mailbox genügt in jeder .qmail-Datei folgender Eintrag:
`|maildrop $HOME/.mailfilter_uwe`

Dann nutzen alle den Weg, der in der .mailfilter_uwe drinsteht: Mail CRM114 zeigen und dann an die Mailbox 'uwe'.

Um deine Nachvollziehbarkeit zur erhöhen würde ich dir empfehlen, den Maildrop-Eintrag als zweite Zeile in der .qmail-Datei anzulegen und das, was vorher drin stand, mit einem #-Zeichen vorweg in einen Kommentar umzuwandeln. Somit wird die Zeile "inaktiv", du kannst sie aber relativ einfach wieder aktivieren (und zum Beispiel vor |maildrop... ein # setzen). Ich würde also empfehlen, dass in allen .qmail-Alias-Dateien, deren Mails auf die Mailbox 'uwe' laufen, folgendes drinsteht:

```
#./users/uwe
|maildrop $HOME/.mailfilter_uwe
```

So sollte es klappen!
Gib bitte noch kurz Rückmeldung, ob dem so ist. Dann kann ich das Issue hier schließen ;)

Viele Grüße!

**Comment by lanebe** [comment]
Hallo,
es klappt alles wie es soll, vielen Dank für die Geduld und Mühe.
Vielleicht kannst Du die Punkte mit den Alias Mails noch in die gute Anleitung packen.

Gruß

**Comment by flowdx** [comment]
Freut mich und Danke für das Lob!
Das mit den Alias kommt auf die Liste.
